### PR TITLE
[WIP] Ui

### PR DESCRIPTION
**Pull request by huangyz0918**
This is an awesome work @tc-imba , thanks so much! 
I have filed this PR from the `ui` branch and marked as `WIP`, so that we can track the code changes with `master`. Once you are ready, ping me and I'll merge that into `master`.

One thing that I found that when I use `tab` to trigger the auto-suggestion, not every time the suggest list will show. I don't know why, as for the previous web version in the `web` folder, there is no such issue. I think maybe we can give a feedback when the backend has some errors, our users can know what happen and can stop waiting and trying.

### CODE REVIEW

**Comment by tc-imba** [comment]
The conditions of when tab will be used to toggle autocomplete or just a normal tab character may be modified. I'll also add a backend error tip when an error is caught in the fetch.

I think the backend problem is most likely to be triggered by "24_token", can you verify about this?

**Comment by huangyz0918** [comment]
> I think the backend problem is most likely to be triggered by "24_token", can you verify about this?

Yes @tc-imba , I have uploaded a new model `keras` , and this model was tested we can use that for the further developments.

**Comment by tc-imba** [comment]
> > I think the backend problem is most likely to be triggered by "24_token", can you verify about this?
> 
> Yes @tc-imba , I have uploaded a new model `keras` , and this model was tested we can use that for the further developments.

It gives the error: AttributeError: 'list' object has no attribute 'items', same as the error in "24_token".
Which version of keras are you using? I'm using tensorflow 2.1.0 with its built-in keras

**Comment by huangyz0918** [comment]
tensorflow 1.14.0, I use this to train the DNN models. @tc-imba 
You are working well with tensorflow 2.1.0?

**Comment by tc-imba** [comment]
> tensorflow 1.14.0, I use this to train the DNN models. @tc-imba
> You are working well with tensorflow 2.1.0?

Yes, actually I encountered other errors when using tf 1.x, and the models "1k_token", "500_token", "test_30_token" should be fine with tf 2.1. Can you check what's the problem?

**Comment by huangyz0918** [comment]
> Yes, actually I encountered other errors when using tf 1.x, and the models "1k_token", "500_token", "test_30_token" should be fine with tf 2.1. Can you check what's the problem?

Sure!
